name: 'CD'
on: 
  push:
    branches: [main]
jobs:
    build:
      defaults:
        run:
          working-directory: ./cinescope
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version: 3.13.7
        - name: build apk
          run: flutter build apk
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: |
              build/app/outputs/apk/release/app-release.apk
              Release.txt
              LICENSE