name: 'CI'
on: 
  push:
    branches: [main]
  pull_request:
jobs:
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cinescope
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.7
      - name: Get dependencies
        run: flutter pub get
      - name: Run Linter
        run: flutter analyze .
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.7
      - name: Run Format
        run: dart format . --set-exit-if-changed
  

